version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schedule
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mailer:
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080
      - 1025:1025

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
